import { StyleSheet } from 'react-native';
import { Colors } from './Colors';

export const TextDisplayStyles = StyleSheet.create({
  imageContainer: {
    marginBottom: 24,
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: Colors.text,
    marginBottom: 16,
    letterSpacing: -0.25,
  },
  capturedImage: {
    width: '100%',
    height: 320,
    borderRadius: 16,
    resizeMode: 'cover',
    backgroundColor: Colors.surfaceVariant,
  },
  processingContainer: {
    alignItems: 'center',
    paddingVertical: 40,
    paddingHorizontal: 24,
  },
  processingText: {
    marginTop: 16,
    fontSize: 16,
    color: Colors.textSecondary,
    fontWeight: '500',
    textAlign: 'center',
  },
  textContainer: {
    backgroundColor: Colors.surface,
    marginHorizontal: 4,
    marginBottom: 24,
    borderRadius: 20,
    padding: 20,
    elevation: 2,
    shadowColor: Colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
  },
  textHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  copyButton: {
    backgroundColor: Colors.info,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    elevation: 1,
    shadowColor: Colors.shadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  copyButtonText: {
    color: Colors.white,
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 0.25,
  },
  textBox: {
    backgroundColor: Colors.surfaceVariant,
    padding: 20,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.border,
    minHeight: 120,
  },
  recognizedText: {
    fontSize: 16,
    color: Colors.text,
    lineHeight: 26,
    fontWeight: '400',
  },
  languageText: {
    fontSize: 14,
    color: Colors.textTertiary,
    marginTop: 12,
    marginBottom: 20,
    fontStyle: 'italic',
    fontWeight: '500',
  },
  actionButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 8,
  },
  saveButton: {
    backgroundColor: Colors.success,
    flex: 1,
  },
  newPhotoButton: {
    backgroundColor: Colors.primary,
    flex: 1,
  },
});
